

ligatures = [{'chars': [36], 'firacode_ligature_name': None},
	{'chars': [37], 'firacode_ligature_name': None},
	{'chars': [38], 'firacode_ligature_name': None},
	{'chars': [124], 'firacode_ligature_name': None},
	{'chars': [172], 'firacode_ligature_name': None},
	{'chars': [173], 'firacode_ligature_name': None},
	{'chars': [176], 'firacode_ligature_name': None},
	{'chars': [177], 'firacode_ligature_name': None},
	{'chars': [178], 'firacode_ligature_name': None},
	{'chars': [179], 'firacode_ligature_name': None},
	{'chars': [185], 'firacode_ligature_name': None},
	{'chars': [215], 'firacode_ligature_name': None},
	{'chars': [216], 'firacode_ligature_name': None},
	{'chars': [223], 'firacode_ligature_name': None},
	{'chars': [229], 'firacode_ligature_name': None},
	{'chars': [230], 'firacode_ligature_name': None},
	{'chars': [247], 'firacode_ligature_name': None},
	{'chars': [248], 'firacode_ligature_name': None},
	{'chars': [322], 'firacode_ligature_name': None},
	{'chars': [338], 'firacode_ligature_name': None},
	{'chars': [339], 'firacode_ligature_name': None},
	{'chars': [711], 'firacode_ligature_name': None},
	{'chars': [717], 'firacode_ligature_name': None},
	{'chars': [913], 'firacode_ligature_name': None},
	{'chars': [914], 'firacode_ligature_name': None},
	{'chars': [915], 'firacode_ligature_name': None},
	{'chars': [916], 'firacode_ligature_name': None},
	{'chars': [917], 'firacode_ligature_name': None},
	{'chars': [918], 'firacode_ligature_name': None},
	{'chars': [919], 'firacode_ligature_name': None},
	{'chars': [920], 'firacode_ligature_name': None},
	{'chars': [921], 'firacode_ligature_name': None},
	{'chars': [922], 'firacode_ligature_name': None},
	{'chars': [923], 'firacode_ligature_name': None},
	{'chars': [924], 'firacode_ligature_name': None},
	{'chars': [925], 'firacode_ligature_name': None},
	{'chars': [926], 'firacode_ligature_name': None},
	{'chars': [927], 'firacode_ligature_name': None},
	{'chars': [928], 'firacode_ligature_name': None},
	{'chars': [929], 'firacode_ligature_name': None},
	{'chars': [931], 'firacode_ligature_name': None},
	{'chars': [932], 'firacode_ligature_name': None},
	{'chars': [933], 'firacode_ligature_name': None},
	{'chars': [934], 'firacode_ligature_name': None},
	{'chars': [935], 'firacode_ligature_name': None},
	{'chars': [936], 'firacode_ligature_name': None},
	{'chars': [937], 'firacode_ligature_name': None},
	{'chars': [945], 'firacode_ligature_name': None},
	{'chars': [946], 'firacode_ligature_name': None},
	{'chars': [947], 'firacode_ligature_name': None},
	{'chars': [948], 'firacode_ligature_name': None},
	{'chars': [949], 'firacode_ligature_name': None},
	{'chars': [949], 'firacode_ligature_name': None},
	{'chars': [950], 'firacode_ligature_name': None},
	{'chars': [951], 'firacode_ligature_name': None},
	{'chars': [952], 'firacode_ligature_name': None},
	{'chars': [953], 'firacode_ligature_name': None},
	{'chars': [954], 'firacode_ligature_name': None},
	{'chars': [955], 'firacode_ligature_name': None},
	{'chars': [956], 'firacode_ligature_name': None},
	{'chars': [957], 'firacode_ligature_name': None},
	{'chars': [958], 'firacode_ligature_name': None},
	{'chars': [959], 'firacode_ligature_name': None},
	{'chars': [960], 'firacode_ligature_name': None},
	{'chars': [961], 'firacode_ligature_name': None},
	{'chars': [962], 'firacode_ligature_name': None},
	{'chars': [963], 'firacode_ligature_name': None},
	{'chars': [964], 'firacode_ligature_name': None},
	{'chars': [965], 'firacode_ligature_name': None},
	{'chars': [966], 'firacode_ligature_name': None},
	{'chars': [967], 'firacode_ligature_name': None},
	{'chars': [968], 'firacode_ligature_name': None},
	{'chars': [969], 'firacode_ligature_name': None},
	{'chars': [977], 'firacode_ligature_name': None},
	{'chars': [981], 'firacode_ligature_name': None},
	{'chars': [982], 'firacode_ligature_name': None},
	{'chars': [1008], 'firacode_ligature_name': None},
	{'chars': [1009], 'firacode_ligature_name': None},
	{'chars': [1031], 'firacode_ligature_name': None},
	{'chars': [1066], 'firacode_ligature_name': None},
	{'chars': [1068], 'firacode_ligature_name': None},
	{'chars': [1098], 'firacode_ligature_name': None},
	{'chars': [1100], 'firacode_ligature_name': None},
	{'chars': [8195], 'firacode_ligature_name': None},
	{'chars': [8201], 'firacode_ligature_name': None},
	{'chars': [8211], 'firacode_ligature_name': None},
	{'chars': [8212], 'firacode_ligature_name': None},
	{'chars': [8224], 'firacode_ligature_name': None},
	{'chars': [8225], 'firacode_ligature_name': None},
	{'chars': [8230], 'firacode_ligature_name': None},
	{'chars': [8230], 'firacode_ligature_name': None},
	{'chars': [8242], 'firacode_ligature_name': None},
	{'chars': [8254], 'firacode_ligature_name': None},
	{'chars': [8304], 'firacode_ligature_name': None},
	{'chars': [8308], 'firacode_ligature_name': None},
	{'chars': [8309], 'firacode_ligature_name': None},
	{'chars': [8310], 'firacode_ligature_name': None},
	{'chars': [8311], 'firacode_ligature_name': None},
	{'chars': [8320], 'firacode_ligature_name': None},
	{'chars': [8321], 'firacode_ligature_name': None},
	{'chars': [8322], 'firacode_ligature_name': None},
	{'chars': [8323], 'firacode_ligature_name': None},
	{'chars': [8324], 'firacode_ligature_name': None},
	{'chars': [8325], 'firacode_ligature_name': None},
	{'chars': [8326], 'firacode_ligature_name': None},
	{'chars': [8327], 'firacode_ligature_name': None},
	{'chars': [8328], 'firacode_ligature_name': None},
	{'chars': [8329], 'firacode_ligature_name': None},
	{'chars': [8494], 'firacode_ligature_name': None},
	{'chars': [8501], 'firacode_ligature_name': None},
	{'chars': [8504], 'firacode_ligature_name': None},
	{'chars': [8592], 'firacode_ligature_name': None},
	{'chars': [8594], 'firacode_ligature_name': None},
	{'chars': [8594], 'firacode_ligature_name': None},
	{'chars': [8614], 'firacode_ligature_name': None},
	{'chars': [8634], 'firacode_ligature_name': None},
	{'chars': [8658], 'firacode_ligature_name': None},
	{'chars': [8660], 'firacode_ligature_name': None},
	{'chars': [8704], 'firacode_ligature_name': None},
	{'chars': [8707], 'firacode_ligature_name': None},
	{'chars': [8708], 'firacode_ligature_name': None},
	{'chars': [8709], 'firacode_ligature_name': None},
	{'chars': [8711], 'firacode_ligature_name': None},
	{'chars': [8712], 'firacode_ligature_name': None},
	{'chars': [8715], 'firacode_ligature_name': None},
	{'chars': [8723], 'firacode_ligature_name': None},
	{'chars': [8724], 'firacode_ligature_name': None},
	{'chars': [8726], 'firacode_ligature_name': None},
	{'chars': [8727], 'firacode_ligature_name': None},
	{'chars': [8728], 'firacode_ligature_name': None},
	{'chars': [8730], 'firacode_ligature_name': None},
	{'chars': [8733], 'firacode_ligature_name': None},
	{'chars': [8734], 'firacode_ligature_name': None},
	{'chars': [8737], 'firacode_ligature_name': None},
	{'chars': [8739], 'firacode_ligature_name': None},
	{'chars': [8740], 'firacode_ligature_name': None},
	{'chars': [8741], 'firacode_ligature_name': None},
	{'chars': [8742], 'firacode_ligature_name': None},
	{'chars': [8743], 'firacode_ligature_name': None},
	{'chars': [8744], 'firacode_ligature_name': None},
	{'chars': [8746], 'firacode_ligature_name': None},
	{'chars': [8748], 'firacode_ligature_name': None},
	{'chars': [8749], 'firacode_ligature_name': None},
	{'chars': [8756], 'firacode_ligature_name': None},
	{'chars': [8757], 'firacode_ligature_name': None},
	{'chars': [8764], 'firacode_ligature_name': None},
	{'chars': [8773], 'firacode_ligature_name': None},
	{'chars': [8776], 'firacode_ligature_name': None},
	{'chars': [8781], 'firacode_ligature_name': None},
	{'chars': [8784], 'firacode_ligature_name': None},
	{'chars': [8790], 'firacode_ligature_name': None},
	{'chars': [8791], 'firacode_ligature_name': None},
	{'chars': [8800], 'firacode_ligature_name': None},
	{'chars': [8800], 'firacode_ligature_name': None},
	{'chars': [8801], 'firacode_ligature_name': None},
	{'chars': [8804], 'firacode_ligature_name': None},
	{'chars': [8805], 'firacode_ligature_name': None},
	{'chars': [8808], 'firacode_ligature_name': None},
	{'chars': [8809], 'firacode_ligature_name': None},
	{'chars': [8810], 'firacode_ligature_name': None},
	{'chars': [8811], 'firacode_ligature_name': None},
	{'chars': [8817], 'firacode_ligature_name': None},
	{'chars': [8822], 'firacode_ligature_name': None},
	{'chars': [8826], 'firacode_ligature_name': None},
	{'chars': [8827], 'firacode_ligature_name': None},
	{'chars': [8834], 'firacode_ligature_name': None},
	{'chars': [8835], 'firacode_ligature_name': None},
	{'chars': [8838], 'firacode_ligature_name': None},
	{'chars': [8839], 'firacode_ligature_name': None},
	{'chars': [8842], 'firacode_ligature_name': None},
	{'chars': [8843], 'firacode_ligature_name': None},
	{'chars': [8853], 'firacode_ligature_name': None},
	{'chars': [8854], 'firacode_ligature_name': None},
	{'chars': [8855], 'firacode_ligature_name': None},
	{'chars': [8856], 'firacode_ligature_name': None},
	{'chars': [8857], 'firacode_ligature_name': None},
	{'chars': [8868], 'firacode_ligature_name': None},
	{'chars': [8869], 'firacode_ligature_name': None},
	{'chars': [8869], 'firacode_ligature_name': None},
	{'chars': [8871], 'firacode_ligature_name': None},
	{'chars': [8901], 'firacode_ligature_name': None},
	{'chars': [8902], 'firacode_ligature_name': None},
	{'chars': [8904], 'firacode_ligature_name': None},
	{'chars': [8914], 'firacode_ligature_name': None},
	{'chars': [8915], 'firacode_ligature_name': None},
	{'chars': [8920], 'firacode_ligature_name': None},
	{'chars': [8921], 'firacode_ligature_name': None},
	{'chars': [8942], 'firacode_ligature_name': None},
	{'chars': [8945], 'firacode_ligature_name': None},
	{'chars': [9632], 'firacode_ligature_name': None},
	{'chars': [9711], 'firacode_ligature_name': None},
	{'chars': [10003], 'firacode_ligature_name': None},
	{'chars': ['-', '-'], 'firacode_ligature_name': 8211},
	{'chars': ['-', '-', '-'], 'firacode_ligature_name': 8212},
	{'chars': ['\\', '"', 'I'], 'firacode_ligature_name': 1031},
	{'chars': ['\\', '$'], 'firacode_ligature_name': 36},
	{'chars': ['\\', '%'], 'firacode_ligature_name': 37},
	{'chars': ['\\', '&'], 'firacode_ligature_name': 38},
	{'chars': ['\\', ','], 'firacode_ligature_name': 8201},
	{'chars': ['\\', '-'], 'firacode_ligature_name': 173},
	{'chars': ['\\', '='], 'firacode_ligature_name': 8254},
	{'chars': ['\\', 'A', 'E'], 'firacode_ligature_name': 198},
	{'chars': ['\\', 'A', 'l', 'p', 'h', 'a'], 'firacode_ligature_name': 913},
	{'chars': ['\\', 'B', 'e', 't', 'a'], 'firacode_ligature_name': 914},
	{'chars': ['\\', 'C', 'a', 'p'], 'firacode_ligature_name': 8914},
	{'chars': ['\\', 'C', 'd', 'p', 'r', 'i', 'm', 'e'], 'firacode_ligature_name': 1066},
	{'chars': ['\\', 'C', 'h', 'i'], 'firacode_ligature_name': 935},
	{'chars': ['\\', 'C', 'p', 'r', 'i', 'm', 'e'], 'firacode_ligature_name': 1068},
	{'chars': ['\\', 'C', 'u', 'p'], 'firacode_ligature_name': 8915},
	{'chars': ['\\', 'D', 'e', 'l', 't', 'a'], 'firacode_ligature_name': 916},
	{'chars': ['\\', 'E', 'p', 's', 'i', 'l', 'o', 'n'], 'firacode_ligature_name': 917},
	{'chars': ['\\', 'E', 't', 'a'], 'firacode_ligature_name': 919},
	{'chars': ['\\', 'G', 'a', 'm', 'm', 'a'], 'firacode_ligature_name': 915},
	{'chars': ['\\', 'I', 'o', 't', 'a'], 'firacode_ligature_name': 921},
	{'chars': ['\\', 'K', 'a', 'p', 'p', 'a'], 'firacode_ligature_name': 922},
	{'chars': ['\\', 'L'], 'firacode_ligature_name': 321},
	{'chars': ['\\', 'L', 'a', 'm', 'b', 'd', 'a'], 'firacode_ligature_name': 923},
	{'chars': ['\\', 'M', 'u'], 'firacode_ligature_name': 924},
	{'chars': ['\\', 'N', 'u'], 'firacode_ligature_name': 925},
	{'chars': ['\\', 'O'], 'firacode_ligature_name': 216},
	{'chars': ['\\', 'O', 'E'], 'firacode_ligature_name': 338},
	{'chars': ['\\', 'O', 'm', 'e', 'g', 'a'], 'firacode_ligature_name': 937},
	{'chars': ['\\', 'O', 'm', 'i', 'c', 'r', 'o', 'n'], 'firacode_ligature_name': 927},
	{'chars': ['\\', 'P', 'h', 'i'], 'firacode_ligature_name': 934},
	{'chars': ['\\', 'P', 'i'], 'firacode_ligature_name': 928},
	{'chars': ['\\', 'P', 's', 'i'], 'firacode_ligature_name': 936},
	{'chars': ['\\', 'R', 'h', 'o'], 'firacode_ligature_name': 929},
	{'chars': ['\\', 'R', 'i', 'g', 'h', 't', 'a', 'r', 'r', 'o', 'w'], 'firacode_ligature_name': 8658},
	{'chars': ['\\', 'S', 'i', 'g', 'm', 'a'], 'firacode_ligature_name': 931},
	{'chars': ['\\', 'T', 'a', 'u'], 'firacode_ligature_name': 932},
	{'chars': ['\\', 'T', 'h', 'e', 't', 'a'], 'firacode_ligature_name': 920},
	{'chars': ['\\', 'U', 'p', 's', 'i', 'l', 'o', 'n'], 'firacode_ligature_name': 933},
	{'chars': ['\\', 'X', 'i'], 'firacode_ligature_name': 926},
	{'chars': ['\\', 'Z', 'e', 't', 'a'], 'firacode_ligature_name': 918},
	{'chars': ['\\', 'a', 'e'], 'firacode_ligature_name': 230},
	{'chars': ['\\', 'a', 'l', 'e', 'p', 'h'], 'firacode_ligature_name': 8501},
	{'chars': ['\\', 'a', 'l', 'p', 'h', 'a'], 'firacode_ligature_name': 945},
	{'chars': ['\\', 'a', 'p', 'p', 'r', 'o', 'x'], 'firacode_ligature_name': 8776},
	{'chars': ['\\', 'a', 's', 't'], 'firacode_ligature_name': 8727},
	{'chars': ['\\', 'a', 's', 'y', 'm', 'p'], 'firacode_ligature_name': 8781},
	{'chars': ['\\', 'b', 'e', 'c', 'a', 'u', 's', 'e'], 'firacode_ligature_name': 8757},
	{'chars': ['\\', 'b', 'e', 't', 'a'], 'firacode_ligature_name': 946},
	{'chars': ['\\', 'b', 'i', 'g', 'c', 'i', 'r', 'c'], 'firacode_ligature_name': 9711},
	{'chars': ['\\', 'b', 'o', 't'], 'firacode_ligature_name': 8869},
	{'chars': ['\\', 'b', 'o', 'w', 't', 'i', 'e'], 'firacode_ligature_name': 8904},
	{'chars': ['\\', 'c', 'a', 'p'], 'firacode_ligature_name': 8745},
	{'chars': ['\\', 'c', 'd', 'o', 't'], 'firacode_ligature_name': 8901},
	{'chars': ['\\', 'c', 'd', 'p', 'r', 'i', 'm', 'e'], 'firacode_ligature_name': 1098},
	{'chars': ['\\', 'c', 'h', 'e', 'c', 'k'], 'firacode_ligature_name': 711},
	{'chars': ['\\', 'c', 'h', 'e', 'c', 'k', 'm', 'a', 'r', 'k'], 'firacode_ligature_name': 10003},
	{'chars': ['\\', 'c', 'h', 'i'], 'firacode_ligature_name': 967},
	{'chars': ['\\', 'c', 'i', 'r', 'c'], 'firacode_ligature_name': 8728},
	{'chars': ['\\', 'c', 'i', 'r', 'c', 'e', 'q'], 'firacode_ligature_name': 8791},
	{'chars': ['\\', 'c', 'o', 'm', 'p', 'l', 'e', 'm', 'e', 'n', 't'], 'firacode_ligature_name': 8705},
	{'chars': ['\\', 'c', 'o', 'n', 'g'], 'firacode_ligature_name': 8773},
	{'chars': ['\\', 'c', 'p', 'r', 'i', 'm', 'e'], 'firacode_ligature_name': 1100},
	{'chars': ['\\', 'c', 'u', 'p'], 'firacode_ligature_name': 8746},
	{'chars': ['\\', 'd', 'a', 'g'], 'firacode_ligature_name': 8224},
	{'chars': ['\\', 'd', 'a', 'l', 'e', 't', 'h'], 'firacode_ligature_name': 8504},
	{'chars': ['\\', 'd', 'd', 'a', 'g'], 'firacode_ligature_name': 8225},
	{'chars': ['\\', 'd', 'd', 'o', 't', 's'], 'firacode_ligature_name': 8945},
	{'chars': ['\\', 'd', 'e', 'g', 'r', 'e', 'e'], 'firacode_ligature_name': 176},
	{'chars': ['\\', 'd', 'e', 'l', 't', 'a'], 'firacode_ligature_name': 948},
	{'chars': ['\\', 'd', 'i', 'v'], 'firacode_ligature_name': 247},
	{'chars': ['\\', 'd', 'o', 't', 'e', 'q'], 'firacode_ligature_name': 8784},
	{'chars': ['\\', 'd', 'o', 't', 'p', 'l', 'u', 's'], 'firacode_ligature_name': 8724},
	{'chars': ['\\', 'd', 'o', 't', 's'], 'firacode_ligature_name': 8230},
	{'chars': ['\\', 'e', 'm', 'p', 't', 'y', 's', 'e', 't'], 'firacode_ligature_name': 8709},
	{'chars': ['\\', 'e', 'p', 's', 'i', 'l', 'o', 'n'], 'firacode_ligature_name': 949},
	{'chars': ['\\', 'e', 'q', 'c', 'i', 'r', 'c'], 'firacode_ligature_name': 8790},
	{'chars': ['\\', 'e', 'q', 'u', 'i', 'v'], 'firacode_ligature_name': 8801},
	{'chars': ['\\', 'e', 's', 't', 'i', 'm', 'a', 't', 'e', 'd'], 'firacode_ligature_name': 8494},
	{'chars': ['\\', 'e', 't', 'a'], 'firacode_ligature_name': 951},
	{'chars': ['\\', 'e', 'x', 'i', 's', 't', 's'], 'firacode_ligature_name': 8707},
	{'chars': ['\\', 'f', 'o', 'r', 'a', 'l', 'l'], 'firacode_ligature_name': 8704},
	{'chars': ['\\', 'g', 'a', 'm', 'm', 'a'], 'firacode_ligature_name': 947},
	{'chars': ['\\', 'g', 'e', 'q'], 'firacode_ligature_name': 8805},
	{'chars': ['\\', 'g', 'g'], 'firacode_ligature_name': 8811},
	{'chars': ['\\', 'g', 'g', 'g'], 'firacode_ligature_name': 8921},
	{'chars': ['\\', 'g', 'n', 'e', 'q'], 'firacode_ligature_name': 8809},
	{'chars': ['\\', 'i', 'f', 'f'], 'firacode_ligature_name': 8660},
	{'chars': ['\\', 'i', 'i', 'i', 'n', 't'], 'firacode_ligature_name': 8749},
	{'chars': ['\\', 'i', 'i', 'n', 't'], 'firacode_ligature_name': 8748},
	{'chars': ['\\', 'i', 'n'], 'firacode_ligature_name': 8712},
	{'chars': ['\\', 'i', 'n', 'f', 't', 'y'], 'firacode_ligature_name': 8734},
	{'chars': ['\\', 'i', 'o', 't', 'a'], 'firacode_ligature_name': 953},
	{'chars': ['\\', 'k', 'a', 'p', 'p', 'a'], 'firacode_ligature_name': 954},
	{'chars': ['\\', 'l'], 'firacode_ligature_name': 322},
	{'chars': ['\\', 'l', 'a', 'm', 'b', 'd', 'a'], 'firacode_ligature_name': 955},
	{'chars': ['\\', 'l', 'd', 'o', 't', 's'], 'firacode_ligature_name': 8230},
	{'chars': ['\\', 'l', 'e', 'f', 't', 'a', 'r', 'r', 'o', 'w'], 'firacode_ligature_name': 8592},
	{'chars': ['\\', 'l', 'e', 'q'], 'firacode_ligature_name': 8804},
	{'chars': ['\\', 'l', 'e', 's', 's', 'g', 't', 'r'], 'firacode_ligature_name': 8822},
	{'chars': ['\\', 'l', 'l'], 'firacode_ligature_name': 8810},
	{'chars': ['\\', 'l', 'l', 'l'], 'firacode_ligature_name': 8920},
	{'chars': ['\\', 'l', 'n', 'e', 'q'], 'firacode_ligature_name': 8808},
	{'chars': ['\\', 'l', 'n', 'o', 't'], 'firacode_ligature_name': 172},
	{'chars': ['\\', 'm', 'a', 'p', 's', 't', 'o'], 'firacode_ligature_name': 8614},
	{'chars': ['\\', 'm', 'e', 'a', 's', 'u', 'r', 'e', 'd', 'a', 'n', 'g', 'l', 'e'], 'firacode_ligature_name': 8737},
	{'chars': ['\\', 'm', 'i', 'd'], 'firacode_ligature_name': 8739},
	{'chars': ['\\', 'm', 'o', 'd', 'e', 'l', 's'], 'firacode_ligature_name': 8871},
	{'chars': ['\\', 'm', 'p'], 'firacode_ligature_name': 8723},
	{'chars': ['\\', 'm', 'u'], 'firacode_ligature_name': 956},
	{'chars': ['\\', 'n', 'a', 'l', 'b', 'a'], 'firacode_ligature_name': 8711},
	{'chars': ['\\', 'n', 'e'], 'firacode_ligature_name': 8800},
	{'chars': ['\\', 'n', 'e', 'q'], 'firacode_ligature_name': 8800},
	{'chars': ['\\', 'n', 'e', 'x', 'i', 's', 't', 's'], 'firacode_ligature_name': 8708},
	{'chars': ['\\', 'n', 'g', 'e', 'q'], 'firacode_ligature_name': 8817},
	{'chars': ['\\', 'n', 'i'], 'firacode_ligature_name': 8715},
	{'chars': ['\\', 'n', 'm', 'i', 'd'], 'firacode_ligature_name': 8740},
	{'chars': ['\\', 'n', 'p', 'a', 'r', 'a', 'l', 'l', 'e', 'l'], 'firacode_ligature_name': 8742},
	{'chars': ['\\', 'n', 'u'], 'firacode_ligature_name': 957},
	{'chars': ['\\', 'o'], 'firacode_ligature_name': 248},
	{'chars': ['\\', 'o', 'd', 'o', 't'], 'firacode_ligature_name': 8857},
	{'chars': ['\\', 'o', 'e'], 'firacode_ligature_name': 339},
	{'chars': ['\\', 'o', 'm', 'e', 'g', 'a'], 'firacode_ligature_name': 969},
	{'chars': ['\\', 'o', 'm', 'i', 'c', 'r', 'o', 'n'], 'firacode_ligature_name': 959},
	{'chars': ['\\', 'o', 'm', 'i', 'n', 'u', 's'], 'firacode_ligature_name': 8854},
	{'chars': ['\\', 'o', 'p', 'l', 'u', 's'], 'firacode_ligature_name': 8853},
	{'chars': ['\\', 'o', 's', 'l', 'a', 's', 'h'], 'firacode_ligature_name': 8856},
	{'chars': ['\\', 'o', 't', 'i', 'm', 'e', 's'], 'firacode_ligature_name': 8855},
	{'chars': ['\\', 'p', 'a', 'r', 'a', 'l', 'l', 'e', 'l'], 'firacode_ligature_name': 8741},
	{'chars': ['\\', 'p', 'e', 'r', 'p'], 'firacode_ligature_name': 8869},
	{'chars': ['\\', 'p', 'h', 'i'], 'firacode_ligature_name': 981},
	{'chars': ['\\', 'p', 'i'], 'firacode_ligature_name': 960},
	{'chars': ['\\', 'p', 'm'], 'firacode_ligature_name': 177},
	{'chars': ['\\', 'p', 'r', 'e', 'c'], 'firacode_ligature_name': 8826},
	{'chars': ['\\', 'p', 'r', 'i', 'm', 'e'], 'firacode_ligature_name': 8242},
	{'chars': ['\\', 'p', 'r', 'o', 'p', 't', 'o'], 'firacode_ligature_name': 8733},
	{'chars': ['\\', 'p', 's', 'i'], 'firacode_ligature_name': 968},
	{'chars': ['\\', 'q', 'u', 'a', 'd'], 'firacode_ligature_name': 8195},
	{'chars': ['\\', 'r', 'h', 'o'], 'firacode_ligature_name': 961},
	{'chars': ['\\', 'r', 'i', 'g', 'h', 't', 'a', 'r', 'r', 'o', 'w'], 'firacode_ligature_name': 8594},
	{'chars': ['\\', 's', 'e', 't', 'm', 'i', 'n', 'u', 's'], 'firacode_ligature_name': 8726},
	{'chars': ['\\', 's', 'i', 'g', 'm', 'a'], 'firacode_ligature_name': 963},
	{'chars': ['\\', 's', 'i', 'm'], 'firacode_ligature_name': 8764},
	{'chars': ['\\', 's', 'q', 'r', 't'], 'firacode_ligature_name': 8730},
	{'chars': ['\\', 's', 'q', 'u', 'a', 'r', 'e'], 'firacode_ligature_name': 9632},
	{'chars': ['\\', 's', 's'], 'firacode_ligature_name': 223},
	{'chars': ['\\', 's', 't', 'a', 'r'], 'firacode_ligature_name': 8902},
	{'chars': ['\\', 's', 'u', 'b', 's', 'e', 't'], 'firacode_ligature_name': 8834},
	{'chars': ['\\', 's', 'u', 'b', 's', 'e', 't', 'e', 'q'], 'firacode_ligature_name': 8838},
	{'chars': ['\\', 's', 'u', 'b', 's', 'e', 't', 'n', 'e', 'q'], 'firacode_ligature_name': 8842},
	{'chars': ['\\', 's', 'u', 'c', 'c'], 'firacode_ligature_name': 8827},
	{'chars': ['\\', 's', 'u', 'p', 's', 'e', 't'], 'firacode_ligature_name': 8835},
	{'chars': ['\\', 's', 'u', 'p', 's', 'e', 't', 'e', 'q'], 'firacode_ligature_name': 8839},
	{'chars': ['\\', 's', 'u', 'p', 's', 'e', 't', 'n', 'e', 'q'], 'firacode_ligature_name': 8843},
	{'chars': ['\\', 't', 'a', 'u'], 'firacode_ligature_name': 964},
	{'chars': ['\\', 't', 'h', 'e', 'r', 'e', 'f', 'o', 'r', 'e'], 'firacode_ligature_name': 8756},
	{'chars': ['\\', 't', 'h', 'e', 't', 'a'], 'firacode_ligature_name': 952},
	{'chars': ['\\', 't', 'i', 'm', 'e', 's'], 'firacode_ligature_name': 215},
	{'chars': ['\\', 't', 'o'], 'firacode_ligature_name': 8594},
	{'chars': ['\\', 't', 'o', 'p'], 'firacode_ligature_name': 8868},
	{'chars': ['\\', 'u', 'p', 's', 'i', 'l', 'o', 'n'], 'firacode_ligature_name': 965},
	{'chars': ['\\', 'v', 'a', 'r', 'e', 'p', 's', 'i', 'l', 'o', 'n'], 'firacode_ligature_name': 949},
	{'chars': ['\\', 'v', 'a', 'r', 'k', 'a', 'p', 'p', 'a'], 'firacode_ligature_name': 1008},
	{'chars': ['\\', 'v', 'a', 'r', 'p', 'h', 'i'], 'firacode_ligature_name': 966},
	{'chars': ['\\', 'v', 'a', 'r', 'p', 'i'], 'firacode_ligature_name': 982},
	{'chars': ['\\', 'v', 'a', 'r', 'r', 'h', 'o'], 'firacode_ligature_name': 1009},
	{'chars': ['\\', 'v', 'a', 'r', 's', 'i', 'g', 'm', 'a'], 'firacode_ligature_name': 962},
	{'chars': ['\\', 'v', 'a', 'r', 't', 'h', 'e', 't', 'a'], 'firacode_ligature_name': 977},
	{'chars': ['\\', 'v', 'd', 'o', 't', 's'], 'firacode_ligature_name': 8942},
	{'chars': ['\\', 'v', 'e', 'e'], 'firacode_ligature_name': 8744},
	{'chars': ['\\', 'v', 'e', 'r', 't'], 'firacode_ligature_name': 124},
	{'chars': ['\\', 'w', 'e', 'd', 'g', 'e'], 'firacode_ligature_name': 8743},
	{'chars': ['\\', 'x', 'i'], 'firacode_ligature_name': 958},
	{'chars': ['\\', 'z', 'e', 't', 'a'], 'firacode_ligature_name': 950},
	{'chars': ['^', '0'], 'firacode_ligature_name': 8304},
	{'chars': ['^', '1'], 'firacode_ligature_name': 185},
	{'chars': ['^', '2'], 'firacode_ligature_name': 178},
	{'chars': ['^', '3'], 'firacode_ligature_name': 179},
	{'chars': ['^', '4'], 'firacode_ligature_name': 8308},
	{'chars': ['^', '5'], 'firacode_ligature_name': 8309},
	{'chars': ['^', '6'], 'firacode_ligature_name': 8310},
	{'chars': ['^', '7'], 'firacode_ligature_name': 8311},
	{'chars': ['_', '0'], 'firacode_ligature_name': 8320},
	{'chars': ['_', '1'], 'firacode_ligature_name': 8321},
	{'chars': ['_', '2'], 'firacode_ligature_name': 8322},
	{'chars': ['_', '3'], 'firacode_ligature_name': 8323},
	{'chars': ['_', '4'], 'firacode_ligature_name': 8324},
	{'chars': ['_', '5'], 'firacode_ligature_name': 8325},
	{'chars': ['_', '6'], 'firacode_ligature_name': 8326},
	{'chars': ['_', '7'], 'firacode_ligature_name': 8327},
	{'chars': ['_', '8'], 'firacode_ligature_name': 8328},
	{'chars': ['_', '9'], 'firacode_ligature_name': 8329}]

